cei/admin_view/urls.py
from django.conf.urls import url
from admin_view import views, templates


urlpatterns = [
  url(r'^$', views.adminTop, name='adminTop'),
  url(r'^admin_login/$', views.adminLogin, name='adminLogin'),
  url(r'^user_list/$', views.adminUserList, name='adminUserList'),
  url(r'^user_create/$', views.adminUserEdit, name='adminUserCreate'),
  url(r'^user_single/(?P<user_id>.{1,16})/$', views.adminUserSingle, name='adminUserSingle'),
  url(r'^user_edit/(?P<user_id>.{1,16})/$', views.adminUserEdit, name='adminUserEdit'),
  url(r'^user_delete/(?P<user_id>.{1,16})/$', views.adminUserDelete, name='adminUserDelete'),
  url(r'^user_activate/(?P<user_id>.{1,16})/$', views.adminUserActivate, name='adminUserActivate'),
  url(r'^user_list_deleted/$', views.adminUserListDeleted, name='adminUserListDeleted'),
  url(r'^user_list_search/$', views.adminUserSearch, name='adminUserSearch'),
  url(r'^news_list_admin/$', views.newsListAdmin, name='newsListAdmin'),
  url(r'^news_list_admin/(?P<s_page>\d+)/$', views.newsListAdmin, name='newsListWithPageAdmin'),
  url(r'^news_single_admin/(?P<id>.+)/$', views.newsSingleAdmin, name='newsSingleAdmin'),
  url(r'^news_create/$', views.newsEdit, name='newsCreate'),
  url(r'^news_edit/(?P<id>.+)/$', views.newsEdit, name='newsEdit'),
  url(r'^news_delete/(?P<id>.+)/$', views.newsDelete, name='newsDelete'),
  url(r'^category_list/$', views.categoryList, name='categoryList'),
  url(r'^category_create/$', views.categoryEdit, name='categoryCreate'),
  url(r'^category_edit/(?P<id>.+)/$', views.categoryEdit, name='categoryEdit'),
  url(r'^message/(?P<user_id>\w+)/$', views.adminMessage, name="adminMessage"),
  url(r'^message/(?P<user_id>\w+)/(?P<s_page>\d+)/$', views.adminMessage, name="adminMessageWithPage"),
  url(r'^message_list/$', views.adminMessageList, name="adminMessageList"),
  url(r'^message_list/(?P<s_page>\d+)/$', views.adminMessageList, name='adminMessageListWithPage'),
]

cei/cei/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from news import views
from cei import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^admin_view/', include('admin_view.urls', namespace='admin_view')),
    url(r'^account/', include('userManagement.urls', namespace='user_management')),
    url(r'^message/', include('message.urls', namespace='message')),
]

cei/news/urls.py
from django.conf.urls import url
from news import views, templates

urlpatterns = [
  url(r'^$', views.newsList, name='newsList'),
  url(r'^(?P<s_page>\d+)/$', views.newsList, name='newsListWithPage'),
  url(r'^news_single/(?P<id>.+)/$', views.newsSingle, name='newsSingle'),
]

cei/userManagement/urls.py
from django.conf.urls import url
from userManagement import views, templates

urlpatterns = [
  url(r'^login/$', views.userLogin, name='userLogin'),
  url(r'^create/$', views.userEdit, name='userCreate'),
  url(r'^detail/$', views.userSingle, name='userSingle'),
  url(r'^edit/$', views.userEdit, name='userEdit'),
]

cei/userManagement/models/rank.py
from django.db import models
from colorfield.fields import ColorField

class Rank(models.Model):
  name = models.CharField("ランク名", max_length=1)
  color = ColorField(max_length=8, null=False, blank=False)

  def __str__(self):
    return self.name

cei/userManagement/models/user.py
from django.db import models
from userManagement.models.rank import *


class User(models.Model):
  id = models.CharField("ユーザーID", max_length=32, primary_key=True)
  name = models.CharField("ユーザーネーム", max_length=16, blank=False, null=False)
  password = models.CharField("パスワード", max_length=16, blank=False, null=False)
  phone = models.CharField("電話番号", max_length=13, unique=True, blank=True, null=True)
  mail = models.EmailField("メール", max_length=128, unique=True, blank=True, null=True)
  rank = models.ForeignKey(Rank, verbose_name="ランク", blank=False, null=False)
  company = models.CharField("会社名", max_length=128, blank=True, null=True)
  register_datetime = models.DateTimeField(auto_now=False, auto_now_add=True, blank=True, null=True)
  unregister_datetime = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
  last_login_datetime = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
  enabled = models.BooleanField(default=True)

  def __str__(self):
    return "{} {}".format(self.id, self.name)

cei/userManagement/forms.py
from django.forms import ModelForm, ValidationError, HiddenInput
from .models.user import *
from django.core.validators import validate_email
import re

class userCreateForm(ModelForm):
  class Meta:
    model = User
    fields = (
      'id', 'name', 'password', 'phone', 'mail', 'rank', 'company', 'enabled',
    )
    widgets = {
      'enabled' : HiddenInput
    }


  def clean_id(self):
    id = self.cleaned_data["id"]
    alnum_Reg = re.compile(r'^[a-zA-Z0-9_]+$')
    if alnum_Reg.match(id) == None:
      raise ValidationError("英数のみでIDを入力してください")
    try:
      User.objects.get(id=id)
    except User.DoesNotExist:
      return id
    else:
      raise ValidationError("このIDは既に使用されています。別のIDを指定してください")

  def clean_phone(self):
    phone = self.cleaned_data["phone"]

    if phone == "" or phone == None:
      return phone

    try:
      User.objects.get(phone=phone)
    except User.DoesNotExist:
      return phone
    else:
      raise ValidationError("この電話番号は既に使用されています。別の電話番号を指定してください")

  def clean_mail(self):
    mail = self.cleaned_data["mail"]

    if mail == "" or mail == None:
      return mail

    try:
      validate_email(mail)
    except ValidationError:
      raise ValidationError("正しいメールアドレスを指定してください。")

    if User.objects.filter(mail=mail).count() == 0:
      return mail
    else:
      raise ValidationError("このメールアドレスは既に使用されています。別のメールアドレスを指定してください")

  def __init__(self, *args, **kwargs):
    kwargs.setdefault('label_suffix', '')
    super(userCreateForm, self).__init__(*args, **kwargs)

class userEditForm(ModelForm):
  class Meta:
    model = User
    fields = (
      'id', 'name', 'password', 'phone', 'mail', 'rank', 'company', 'enabled',
    )
    widgets = {
      'id' : HiddenInput,
      'enabled' : HiddenInput
    }

  def clean_phone(self):
    id = self['id'].value()
    phone = self.cleaned_data["phone"]

    if phone == "" or phone == None:
      return phone

    if User.objects.filter(phone=phone).exclude(id=id).count() == 0:
      return phone
    else:
      raise ValidationError("この電話番号は既に使用されています。別の電話番号を指定してください")

  def clean_mail(self):
    id = self['id'].value()
    mail = self.cleaned_data["mail"]

    if mail == "" or mail == None:
      return mail

    try:
      validate_email(mail)
    except ValidationError:
      raise ValidationError("正しいメールアドレスを指定してください。")

    if User.objects.filter(mail=mail).exclude(id=id).count() == 0:
      return mail
    else:
      raise ValidationError("このメールアドレスは既に使用されています。別のメールアドレスを指定してください")

  def __init__(self, *args, **kwargs):
    kwargs.setdefault('label_suffix', '')
    super(userEditForm, self).__init__(*args, **kwargs)

cei/userManagement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib import messages
from datetime import datetime


def userLogin(request):
  if request.method == 'GET':
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_pass = request.POST['cei_pass']
    user_work = User.objects.filter(id=user_id, password=user_pass).values('id', 'password', 'name', 'rank__name', 'rank__color')
    if user_work:
      user = user_work.filter(enabled=True)
      if user:
        lsStore = {
          'cei_id': user[0]['id'],
          'cei_pass': user[0]['password'],
          'cei_name': user[0]['name'],
          'cei_rank_name': user[0]['rank__name'],
          'cei_rank_color': user[0]['rank__color'],
        }
        User.objects.filter(id=user_id).update(last_login_datetime = datetime.now())
        return render(request, 'user_dummy_login.html', dict(lsStore=lsStore))
      else:
        messages.info(request, '会員権の有効期限が切れています。')
        return render(request, 'user_login.html')
    else:
      messages.info(request, 'ユーザーIDまたはパスワードが間違っています。')
      return render(request, 'user_login.html')


def userEdit(request):
  if request.method == 'GET' or 'cei_id' not in request.POST:
    messages.info(request, 'ログインしてください。')
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_work = User.objects.filter(id=user_id)
    if user_work.count() == 0:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'user_login.html')
    else:
      user = user_work[0]
      if request.POST['post_type'] == 'get_page':
        form = userEditForm(instance=user)
        return render(request, 'user_edit.html', dict(form=form, user_id=user.id))
      else:
        form = userEditForm(request.POST, instance=user)
        if form.is_valid():
          user = form.save(commit=False)
          user.save()
          return render(request, 'dummy_user_single.html', dict(user_id=user.id))
        else:
          return render(request, 'user_edit.html', dict(form=form, user_id=user.id))


def userSingle(request):
  if request.method == 'GET' or 'cei_id' not in request.POST:
    messages.info(request, 'ログインしてください。')
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_work = User.objects.filter(id=user_id)
    if user_work.count() == 0:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'user_login.html')
    else:
      if request.POST['post_type'] == 'get_page':
        user = user_work.values('id', 'name', 'phone', 'mail', 'rank__name', 'company', 'password', 'register_datetime')[0]
        return render(request, 'user_single.html', dict(user=user))
      else:
        messages.info(request, '不正なアクセスです。')
        return render(request, 'user_login.html')

cei/userManagement/templates/admin_user_edit.html
{% extends "admin_base.html" %}

{% block title %}
  {% if user_id %}
    ユーザー情報編集
  {% else %}
    ユーザー作成
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        アカウント
      </h4>
      <span>
        >
      </span>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
      <h4>
        {% if user_id %}
          ユーザー情報編集
        {% else %}
          ユーザー作成
        {% endif %}
      </h4>
    </div>
    <div class="main-item">
      <h2>
        {% if user_id %}
          ユーザー情報編集
        {% else %}
          ユーザー作成
        {% endif %}
      </h2>
      <div class="user-edit">
        {% if user_id %}
          <form action="{% url 'admin_view:adminUserEdit' user_id=form.id.value %}" method="post">
        {% else %}
          <form action="{% url 'admin_view:adminUserCreate' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <input type="hidden" name="post_type" value="post">
          <table>
            {{ form.enabled }}
            {% if user_id %}
              {{ form.id }}
            {% else %}
              <tr>
                <th>
                  {{ form.id.label_tag }} <span class="required-span">必須</span>
                </th>
                <td>
                  {{ form.id }}
                </td>
              </tr>
            {% endif %}
            <tr>
              <th>
                {{ form.rank.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.rank }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.company.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.company }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.name.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.name }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.phone.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.phone }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.mail.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.mail }}
              </td>
            </tr>
            <tr class="last-make-border">
              <th>
                {{ form.password.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.password }}
              </td>
            </tr>
          </table>
          <div class="text-right">
            <button type="submit" id="submit" class="submit-btn">保存</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

cei/userManagement/templates/admin_user_list.html
{% extends "admin_base.html" %}

{% block title %}
  {% if user_id %}
    ユーザー情報編集
  {% else %}
    ユーザー作成
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザ一覧
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <div class="main-item-navbar">
        <a href='javascript:getPage("{% url 'admin_view:adminUserList' %}")'>
          <h3 class="main-item-nav active">
            ユーザー&nbsp;一覧
          </h3>
        </a>
        <a href='javascript:getPage("{% url 'admin_view:adminUserListDeleted' %}")'>
          <h3 class="main-item-nav">
            削除済みユーザー&nbsp;一覧
          </h3>
        </a>
        <a href='javascript:getPage("{% url 'admin_view:adminUserCreate' %}")'>
          <h3 class="main-item-nav">
            新規作成
          </h3>
        </a>
      </div>
      <table class="user-list-table">
        <tr>
          <th>
            ランク
          </th>
          <th>
            法人名
          </th>
          <th>
            担当者名
          </th>
          <th>
            最終ログイン日時
          </th>
          <th>
            アクション
          </th>
        </tr>
      <form action="{% url 'admin_view:adminUserSearch' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="enabled" value="True">
        <tr>
          <td>
            <input type="text" name="rank" pattern=".{0,1}">
          </td>
          <td>
            <input type="text" name="company" pattern=".{0-128}">
          </td>
          <td>
            <input type="text" name="name" pattern=".{0-32}">
          </td>
          <td></td>
          <td>
            <button type="submit">検索</button>
          </td>
        </tr>
      </form>
        {% for user in user_list %}
          <tr>
            <td>
              <h4 class="user-list__rank" style="background-color: {{ user.rank__color }}">
                {{ user.rank__name }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__company">
                {{ user.company }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__name">
                {{ user.name }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__name">
                {{ user.last_login_datetime }}
              </h4>
            </td>
            <td>
              <a href='javascript:getPage("{% url 'admin_view:adminMessage' user_id=user.id %}")'>
                チャット画面
              </a>
              <a href='javascript:getPage("{% url 'admin_view:adminUserSingle' user_id=user.id %}")'>
                詳細
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}

cei/userManagement/templates/admin_user_list_deleted.html
{% extends "admin_base.html" %}

{% block title %}
  {% if user_id %}
    ユーザー情報編集
  {% else %}
    ユーザー作成
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        削除済みユーザー一覧
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <div class="main-item-navbar">
        <a href='javascript:getPage("{% url 'admin_view:adminUserList' %}")'>
          <h3 class="main-item-nav">
            ユーザー&nbsp;一覧
          </h3>
        </a>
        <a href='javascript:getPage("{% url 'admin_view:adminUserListDeleted' %}")'>
          <h3 class="main-item-nav active">
            削除済みユーザー&nbsp;一覧
          </h3>
        </a>
        <a href='javascript:getPage("{% url 'admin_view:adminUserCreate' %}")'>
          <h3 class="main-item-nav">
            新規作成
          </h3>
        </a>
      </div>
      <table class="user-list-table">
        <tr>
          <th>
            ランク
          </th>
          <th>
            法人名
          </th>
          <th>
            担当者名
          </th>
          <th>
            最終ログイン日時
          </th>
          <th>
            アクション
          </th>
        </tr>
      <form action="{% url 'admin_view:adminUserSearch' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="enabled" value="False">
        <tr>
          <td>
            <input type="text" name="rank" pattern=".{0,1}">
          </td>
          <td>
            <input type="text" name="company" pattern=".{0-128}">
          </td>
          <td>
            <input type="text" name="name" pattern=".{0-32}">
          </td>
          <td></td>
          <td>
            <button type="submit">検索</button>
          </td>
        </tr>
      </form>
        {% for user in user_list %}
          <tr>
            <td>
              <h4 class="user-list__rank" style="background-color: {{ user.rank__color }}">
                {{ user.rank__name }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__company">
                {{ user.company }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__name">
                {{ user.name }}
              </h4>
            </td>
            <td>
              <h4 class="user-list__name">
                {{ user.last_login_datetime }}
              </h4>
            </td>
            <td>
              <a href='javascript:getPage("{% url 'admin_view:adminMessage' user_id=user.id %}")'>
                チャット画面
              </a>
              <a href='javascript:getPage("{% url 'admin_view:adminUserSingle' user_id=user.id %}")'>
                詳細
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}

cei/userManagement/templates/admin_user_single.html
{% extends "admin_base.html" %}

{% block title %}
  ユーザー詳細
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザー詳細
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <a href='javascript:getPage("{% url 'admin_view:adminUserList' %}")'>
        <h2 class="back-user-btn">
          <　一覧へ戻る
        </h2>
      </a>
      <div class="user-single">
        <table>
          <tr>
            <th>
              ランク
            </th>
            <td>
              {{ user.rank__name }}
            </td>
          </tr>
          <tr>
            <th>
              法人名
            </th>
            <td>
              {{ user.company }}
            </td>
          </tr>
          <tr>
            <th>
              担当者名
            </th>
            <td>
              {{ user.name }}
            </td>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <td>
              {{ user.phone }}
            </td>
          </tr>
          <tr>
            <th>
              メールアドレス
            </th>
            <td>
              {{ user.mail }}
            </td>
          </tr>
          <tr>
            <th>
              パスワード
            </th>
            <td>
              {{ user.password }}
            </td>
          </tr>
          <tr>
            <th>
              登録日
            </th>
            <td>
              {{ user.register_datetime }}
            </td>
          </tr>
          <tr>
            <th>
              最終ログイン日時
            </th>
            <td>
              {{ user.last_login_datetime }}
            </td>
          </tr>
          <tr class="last-make-border">
            <th>
              メッセージ URL
            </th>
            <td>
              {% url 'admin_view:adminMessage' user_id=user.id %}
            </td>
          </tr>
        </table>
      </div>
      <div class="user-single-actions">
        {% if user.enabled %}
          <a href='javascript:getPage("{% url 'admin_view:adminUserDelete' user_id=user.id %}")'>
            <h5 class="single-del-btn">
              削除
            </h5>
          </a>
        {% else %}
          <a href='javascript:getPage("{% url 'admin_view:adminUserActivate' user_id=user.id %}")'>
            <h5 class="revival-btn">
              復活
            </h5>
          </a>
        {% endif %}
        <a href='javascript:getPage("{% url 'admin_view:adminUserEdit' user_id=user.id %}")'>
          <h5>
            編集
          </h5>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

cei/userManagement/templates/dummy_user_single.html
{% extends "base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'get_page' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'cei_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('cei_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'cei_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('cei_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'user_management:userSingle' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/userManagement/templates/user_dummy_login.html
{% extends "base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'user_form' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'cei_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('cei_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'cei_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('cei_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'news:newsList' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/userManagement/templates/user_edit.html
{% extends "base.html" %}

{% block title %}
  ユーザー情報編集
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        アカウント
      </h4>
      <span>
        >
      </span>
      <h4>
        {% if user_id %}
          ユーザー情報編集
        {% else %}
          ユーザー作成
        {% endif %}
      </h4>
      <h4 class="user-box-name">
        <span class="insert-user-rank-name insert-user-rank-color"></span>
        <span class="insert-user-name"></span>
        様
      </h4>
    </div>
    <div class="main-item">
      <h2>
        ユーザー作成
      </h2>
      <div class="user-edit">
        <form action="{% url 'user_management:userEdit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="post_type" value="post">
          <table>
            {{ form.enabled }}
            <input type="hidden" name="cei_id" value="{{ user_id }}">
            {% if user_id %}
              {{ form.id }}
            {% else %}
              <tr>
                <th>
                  {{ form.id.label_tag }} <span class="required-span">必須</span>
                </th>
                <td>
                  {{ form.id }}
                </td>
              </tr>
            {% endif %}
            <tr>
              <th>
                {{ form.rank.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.rank }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.company.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.company }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.name.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.name }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.phone.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.phone }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.mail.label_tag }} <span class="optional-span">任意</span>
              </th>
              <td>
                {{ form.mail }}
              </td>
            </tr>
            <tr>
              <th>
                {{ form.password.label_tag }} <span class="required-span">必須</span>
              </th>
              <td>
                {{ form.password }}
              </td>
            </tr>
          </table>
          <div class="text-right">
            <button type="submit" id="submit" class="submit-btn">保存</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

cei/userManagement/templates/user_single.html
{% extends "base.html" %}

{% block title %}
  ユーザー詳細
{% endblock title %}
{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        管理者ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        ユーザー詳細
      </h4>
      <h4 class="user-box-name">
        <span class="insert-user-rank-name insert-user-rank-color"></span>
        <span class="insert-user-name"></span>
        様
      </h4>
    </div>
    <div class="main-item">
      <h2>
        ユーザー詳細
      </h2>
      <div class="user-single">
        <table>
          <tr>
            <th>
              ランク
            </th>
            <td>
              {{ user.rank__name }}
            </td>
          </tr>
          <tr>
            <th>
              法人名
            </th>
            <td>
              {{ user.company }}
            </td>
          </tr>
          <tr>
            <th>
              担当者名
            </th>
            <td>
              {{ user.name }}
            </td>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <td>
              {{ user.phone }}
            </td>
          </tr>
          <tr>
            <th>
              メールアドレス
            </th>
            <td>
              {{ user.mail }}
            </td>
          </tr>
          <tr>
            <th>
              パスワード
            </th>
            <td>
              {{ user.password }}
            </td>
          </tr>
          <tr>
            <th>
              登録日
            </th>
            <td>
              {{ user.register_datetime }}
            </td>
          </tr>
        </table>
      </div>
      <div class="user-single-actions">
        <a href='javascript:getPage("{% url 'user_management:userEdit' %}")'>
          <h5>
            編集
          </h5>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}