cei/admin_view/urls.py
from django.conf.urls import url
from admin_view import views, templates


urlpatterns = [
  url(r'^$', views.adminTop, name='adminTop'),
  url(r'^admin_login/$', views.adminLogin, name='adminLogin'),
  url(r'^user_list/$', views.adminUserList, name='adminUserList'),
  url(r'^user_create/$', views.adminUserEdit, name='adminUserCreate'),
  url(r'^user_single/(?P<user_id>.{1,16})/$', views.adminUserSingle, name='adminUserSingle'),
  url(r'^user_edit/(?P<user_id>.{1,16})/$', views.adminUserEdit, name='adminUserEdit'),
  url(r'^user_delete/(?P<user_id>.{1,16})/$', views.adminUserDelete, name='adminUserDelete'),
  url(r'^user_activate/(?P<user_id>.{1,16})/$', views.adminUserActivate, name='adminUserActivate'),
  url(r'^user_list_deleted/$', views.adminUserListDeleted, name='adminUserListDeleted'),
  url(r'^user_list_search/$', views.adminUserSearch, name='adminUserSearch'),
  url(r'^news_list_admin/$', views.newsListAdmin, name='newsListAdmin'),
  url(r'^news_list_admin/(?P<s_page>\d+)/$', views.newsListAdmin, name='newsListWithPageAdmin'),
  url(r'^news_single_admin/(?P<id>.+)/$', views.newsSingleAdmin, name='newsSingleAdmin'),
  url(r'^news_create/$', views.newsEdit, name='newsCreate'),
  url(r'^news_edit/(?P<id>.+)/$', views.newsEdit, name='newsEdit'),
  url(r'^news_delete/(?P<id>.+)/$', views.newsDelete, name='newsDelete'),
  url(r'^category_list/$', views.categoryList, name='categoryList'),
  url(r'^category_create/$', views.categoryEdit, name='categoryCreate'),
  url(r'^category_edit/(?P<id>.+)/$', views.categoryEdit, name='categoryEdit'),
  url(r'^message/(?P<user_id>\w+)/$', views.adminMessage, name="adminMessage"),
  url(r'^message/(?P<user_id>\w+)/(?P<s_page>\d+)/$', views.adminMessage, name="adminMessageWithPage"),
  url(r'^message_list/$', views.adminMessageList, name="adminMessageList"),
  url(r'^message_list/(?P<s_page>\d+)/$', views.adminMessageList, name='adminMessageListWithPage'),
]

cei/cei/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from news import views
from cei import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^admin_view/', include('admin_view.urls', namespace='admin_view')),
    url(r'^account/', include('userManagement.urls', namespace='user_management')),
    url(r'^message/', include('message.urls', namespace='message')),
]

cei/admin_view/models.py
from django.db import models

# Create your models here.

cei/admin_view/models/admin.py
from django.db import models

class Admin(models.Model):
  admin_id = models.CharField(primary_key=True, max_length=16, null=False, blank=False)
  admin_pass = models.CharField(max_length=16, null=False, blank=False)
  enabled = models.BooleanField(default=True)

cei/admin_view/forms.py
from django.forms import ModelForm, RadioSelect, Textarea, ValidationError, HiddenInput, BooleanField
from .models.admin import *
from django.forms.widgets import TextInput

class adminForm(ModelForm):
  class Meta:
    model = Admin
    fields = (
      'admin_id', 'admin_pass'
    )
    widgets = {
    }

  def __init__(self, *args, **kwargs):
    kwargs.setdefault('label_suffix', '')
    super(adminForm, self).__init__(*args, **kwargs)

cei/admin_view/views.py
from django.shortcuts import render, redirect, get_object_or_404
import math
from .forms import *
from userManagement.forms import *
from news.forms import *
from message.models.message import *
from django.contrib import messages

# admin_login

def adminTop(request, s_page = '1'):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return redirect('admin_view:adminLogin')
  else:
    admin_id = request.POST['admin_id']
    admin_pass = request.POST['admin_pass']
    admin = Admin.objects.filter(admin_id=admin_id, admin_pass=admin_pass).values('admin_id', 'admin_pass')
    if admin:
      page = int('0' + s_page)
      message_data = Message.objects.filter(enabled=True, read_flag=False, admin_send_flag=False).order_by(
        '-send_datetime')
      last_page = math.floor(message_data.count() / 6) + 1
      pages = []
      for i in range(last_page):
        pages.append(i + 1)
      message_list = message_data[(page - 1) * 6:page * 6].values('user__id', 'user__name', 'text', 'send_datetime',
                                                                  'admin_send_flag', 'read_flag')
      return render(request, 'admin_top.html', dict(message_list=message_list, pages=pages))
    else:
      messages.info(request, 'ユーザーIDまたはパスワードが間違っています。')
      return render(request, 'admin_login.html')


def adminLogin(request):
  if request.method == 'GET':
    return render(request, 'admin_login.html')
  else:
    admin_id = request.POST['admin_id']
    admin_pass = request.POST['admin_pass']
    admin = Admin.objects.filter(admin_id=admin_id, admin_pass=admin_pass).values('admin_id', 'admin_pass')
    if admin:
      return render(request, 'admin_dummy_top.html', dict(lsStore = admin.values('admin_id', 'admin_pass')[0]))
    else:
      messages.info(request, 'ユーザーIDまたはパスワードが間違っています。', dict(lsStore ={'admin_id':'', 'admin_pass':''}))
      return render(request, 'admin_login.html')


# admin_news

def newsListAdmin(request, s_page = '1'):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return redirect('admin_view:adminLogin')
  else:
    page = int('0' + s_page)
    news_data = News.objects.filter(enabled = True).order_by('-post_datetime')
    last_page = math.floor(news_data.count() / 6) + 1
    pages = []
    for i in range(last_page):
      pages.append(i + 1)
    news_list = news_data[(page - 1) * 6:page * 6].values('post_datetime', 'news_category__category_name', 'title', 'news_category__category_color', 'id')
    return render(request, 'admin_news_list.html', dict(news_list=news_list, pages=pages))


def categoryList(request):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return redirect('admin_view:adminLogin')
  else:
    # page = int('0' + s_page)
    category_list = Category.objects.all().order_by('id')
    # last_cate_page = math.floor(category_data.count() / 6) + 1
    pages_cat = []
    # for i in range(last_cate_page):
    #   pages_cat.append(i + 1)
    # category_list = category_data[(page - 1) * 6:page * 6].values('category_name', 'category_color', 'id')
    return render(request, 'admin_category_list.html', dict(category_list=category_list))


def newsSingleAdmin(request, id = None):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if id:
      news = News.objects.filter(id = id, enabled = True).values('id', 'post_datetime', 'news_category__category_name', 'caption', 'title', 'news_category__category_color')[0]
      if news:
        return render(request, 'admin_news_single.html', dict(news=news))
      else:
        messages.info(request, 'ニュースが存在しません。')
        return render(request, 'admin_news_list.html')
    else:
        messages.info(request, '不正なアクセスです。')
        return render(request, 'admin_news_list.html')

def categoryEdit(request, id = None):
  if request.method == "GET":
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if request.POST['post_type'] == 'get_page':
      if id:
        category = get_object_or_404(Category, pk=id)
      else:
        category = Category()
      form = categoryForm(instance=category)
      return render(request, 'admin_category_create.html', dict(form=form, id=id))
    else:
      if id:
        category = get_object_or_404(Category, pk=id)
      else:
        category = Category()
      form = categoryForm(request.POST, instance=category)
      print('1')
      print(form)
      if form.is_valid():
        category = form.save(commit=False)
        category.save()
        return render(request, 'admin_dummy_category.html')
      else:
        messages.info(request, '入力に誤りがあります。')
        return render(request, 'admin_category_create.html', dict(form=form, id=id))


def newsEdit(request, id=None):
  if request.method == "GET":
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if request.POST['post_type'] == 'get_page':
      if id:
        news = get_object_or_404(News, pk=id)
      else:
        news = News()
      form = newsForm(instance=news)
      return render(request, 'admin_news_create.html', dict(form=form, id=id))
    else:
      if id:
        news = get_object_or_404(News, pk=id)
      else:
        news = News()
      form = newsForm(request.POST, instance=news)
      if form.is_valid():
        news = form.save(commit=False)
        news.enabled = True
        news.save()
        return render(request, 'admin_dummy_news.html')
      else:
        messages.info(request, '入力に誤りがあります。')
        return render(request, 'admin_news_create.html', dict(form=form, id=id))


def newsDelete(request, id=None):
  if request.method == "GET":
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if id:
      try:
        news = News.objects.get(id=id, enabled=True)
      except News.DoesNotExist:
        messages.info(request, '選択されたニュースは存在しません。')
        return redirect('admin_view:adminLogin')
      else:
        news.enabled = False
        news.save()
        messages.info(request, '選択されたニュースは削除されました。')
        return render(request, 'admin_dummy_news.html')
    else:
      messages.info(request, '不正なアクセスです。')
      return redirect('admin_view:adminLogin')


def adminUserEdit(request, user_id=None):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if request.POST['post_type'] == 'get_page':
      if user_id:
        user = get_object_or_404(User, id=user_id)
        form = userEditForm(instance=user)
      else:
        user = User()
        form = userCreateForm(instance=user)
      return render(request, 'admin_user_edit.html', dict(form=form, user_id=user_id))
    else:
      if user_id:
        user = get_object_or_404(User, id=user_id)
        form = userEditForm(request.POST, instance=user)
      else:
        user = User()
        form = userCreateForm(request.POST, instance=user)
      if form.is_valid():
        user = form.save(commit=False)
        user.save()
        return render(request, 'admin_dummy_user_single.html', dict(user_id=user.id))
      else:
        return render(request, 'admin_user_edit.html', dict(form=form))



def adminUserSingle(request, user_id=None):
  if user_id:
    if request.method == 'GET':
      messages.info(request, 'ログインしてください。')
      return render(request, 'admin_login.html')
    else:
      if request.POST['post_type'] == 'get_page':
        user = User.objects.filter(id=user_id).values('id', 'name', 'phone', 'mail', 'rank__name', 'company', 'password', 'register_datetime', 'last_login_datetime', 'enabled')[0]
        return render(request, 'admin_user_single.html', dict(user=user))
      else:
        messages.info(request, '不正なアクセスです。')
        return render(request, 'admin_login.html')
  else:
    messages.info(request, '不正なアクセスです。')
    return render(request, 'admin_login.html')


def adminUserList(request):
  if request.method == "GET":
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    user_list = User.objects.filter(enabled=True).values('id', 'name', 'company', 'last_login_datetime', 'rank__name', 'rank__color').order_by('id')
    return render(request, 'admin_user_list.html', dict(user_list=user_list))


def adminUserDelete(request, user_id=None):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if user_id:
      try:
        user = User.objects.get(id=user_id)
      except User.DoesNotExist:
        messages.info(request, '選択されたユーザーは存在しません。')
        return render(request, 'admin_dummy_user_list.html')
      else:
        user.enabled = False
        user.save()
        messages.info(request, '選択されたユーザーを削除しました。')
        return render(request, 'admin_dummy_user_list.html')
    else:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'admin_dummy_top.html')


def adminUserActivate(request, user_id=None):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:
    if user_id:
      try:
        user = User.objects.get(id=user_id)
      except User.DoesNotExist:
        messages.info(request, '選択されたユーザーは存在しません。')
        return render(request, 'admin_dummy_user_list_deleted.html')
      else:
        user.enabled = True
        user.save()
        messages.info(request, '選択されたユーザーを復活しました。')
        return render(request, 'admin_dummy_user_list_deleted.html')
    else:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'admin_dummy_top.html')


def adminUserListDeleted(request):
  if request.method == 'GET':
    messages.info(request, 'ログインしてください。')
    return render(request, 'admin_login.html')
  else:

cei/admin_view/templates/admin_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      <div class="header-menu">
        <h1>CEI,BASE<br>
          <span>管理者ページ</span>
        </h1>
        <div>
          <span>menu</span>
          <a href='javascript:getPage("{% url 'admin_view:newsListAdmin' %}")'>
            <h3><i class="fa fa-exclamation-circle" aria-hidden="true"></i>お知らせ管理</h3>
          </a>
          <a href='javascript:getPage("{% url 'admin_view:adminMessageList' %}")'>
            <h3><i class="fa fa-commenting-o" aria-hidden="true"></i>メッセージ管理</h3>
          </a>
          <a href='javascript:getPage("{% url 'admin_view:adminUserList' %}")'>
            <h3><i class="fa fa-user-circle-o" aria-hidden="true"></i>ユーザ管理</h3>
          </a>
        </div>
      </div>
    </header>
    {% block content %}

    {% endblock %}
    <footer>
    </footer>
{#    <div class="copyright">#}
{#      Copyright &copy; CEI All Rights Reserved.#}
{#    </div>#}
    <script src="https://code.jquery.com/jquery-3.2.1.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootbox.min.js' %}" ></script>
    <script src="{% static 'js/jscolor.js' %}"  crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"  crossorigin="anonymous"></script>
    <script type="text/javascript">
      {% if lsStore %}
        {% for key,value in lsStore.items %}
          localStorage.setItem("{{key}}", "{{value}}");
        {% endfor %}
      {% endif %}
      {% if messages %}
        {% for message in messages %}
          alert('{{ message }}');
        {% endfor %}
      {% endif %}
      {% if form.errors %}
        var errors = new DOMParser().parseFromString('{{ form.errors }}', 'text/html');
        errorList = errors.getElementsByClassName("errorlist")[0].children;
        for(var error_item of errorList){
          for(var error of error_item.children){
            id = 'id_' + error_item.innerHTML.replace(/\<ul.*$/,'');
            text = error.outerText;
            $('#' + id).parents('tr').after('<tr class="no-border"><th></th><td>' + text + '</td></tr>');
          }
        }
      {% endif %}
    </script>
    <script type="text/javascript">
      function postForm(){
        var form = document.createElement( 'form' );
        document.body.appendChild( form );
        var post_type = document.createElement( 'input' );
        post_type.setAttribute( 'type' , 'hidden' );
        post_type.setAttribute( 'name' , 'post_type' );
        post_type.setAttribute( 'value' , 'user_form' );
        var admin_id = document.createElement( 'input' );
        admin_id.setAttribute( 'type' , 'hidden' );
        admin_id.setAttribute( 'name' , 'admin_id' );
        admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
        var admin_pass = document.createElement( 'input' );
        admin_pass.setAttribute( 'type' , 'hidden' );
        admin_pass.setAttribute( 'name' , 'admin_pass' );
        admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
        var csrftoken = document.createElement( 'input' );
        csrftoken.setAttribute( 'type' , 'hidden' );
        csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
        csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
        form.appendChild( post_type );
        form.appendChild( admin_id );
        form.appendChild( admin_pass );
        form.appendChild( csrftoken );
        form.setAttribute( 'action' , '{% url 'admin_view:adminLogin' %}' );
        form.setAttribute( 'method' , 'post' );
        form.submit();
      }
    </script>
    <script type="text/javascript">
      function getPage(url){
        var form = document.createElement( 'form' );
        document.body.appendChild( form );
        var post_type = document.createElement( 'input' );
        post_type.setAttribute( 'type' , 'hidden' );
        post_type.setAttribute( 'name' , 'post_type' );
        post_type.setAttribute( 'value' , 'get_page' );
        var admin_id = document.createElement( 'input' );
        admin_id.setAttribute( 'type' , 'hidden' );
        admin_id.setAttribute( 'name' , 'admin_id' );
        admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
        var admin_pass = document.createElement( 'input' );
        admin_pass.setAttribute( 'type' , 'hidden' );
        admin_pass.setAttribute( 'name' , 'admin_pass' );
        admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
        var csrftoken = document.createElement( 'input' );
        csrftoken.setAttribute( 'type' , 'hidden' );
        csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
        csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
        form.appendChild( post_type );
        form.appendChild( admin_id );
        form.appendChild( admin_pass );
        form.appendChild( csrftoken );
        form.setAttribute( 'action' , url );
        form.setAttribute( 'method' , 'post' );
        form.submit();
      }
    </script>
    {% block js %}{% endblock %}
  </body>
</html>

cei/admin_view/templates/admin_dummy_category.html
{% extends "admin_base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'get_page' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'admin_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'admin_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'admin_view:categoryList' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/admin_view/templates/admin_dummy_news.html
{% extends "admin_base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'get_page' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'admin_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'admin_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'admin_view:newsListAdmin' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/admin_view/templates/admin_dummy_news_create.html
{% extends "admin_base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'get_page' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'admin_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'admin_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'admin_view:newsCreate' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/admin_view/templates/admin_dummy_top.html
{% extends "admin_base.html" %}

{% block js %}
  <script>
   $(function(){
      var form = document.createElement( 'form' );
      document.body.appendChild( form );
      var post_type = document.createElement( 'input' );
      post_type.setAttribute( 'type' , 'hidden' );
      post_type.setAttribute( 'name' , 'post_type' );
      post_type.setAttribute( 'value' , 'user_form' );
      var admin_id = document.createElement( 'input' );
      admin_id.setAttribute( 'type' , 'hidden' );
      admin_id.setAttribute( 'name' , 'admin_id' );
      admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
      var admin_pass = document.createElement( 'input' );
      admin_pass.setAttribute( 'type' , 'hidden' );
      admin_pass.setAttribute( 'name' , 'admin_pass' );
      admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
      var csrftoken = document.createElement( 'input' );
      csrftoken.setAttribute( 'type' , 'hidden' );
      csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
      csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
      form.appendChild( post_type );
      form.appendChild( admin_id );
      form.appendChild( admin_pass );
      form.appendChild( csrftoken );
      form.setAttribute( 'action' , '{% url 'admin_view:adminTop' %}' );
      form.setAttribute( 'method' , 'post' );
      form.submit();
    });
  </script>
{% endblock %}

cei/admin_view/templates/admin_top.html
{% extends "admin_base.html" %}

{% block title %}管理者トップ{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        TOP　新着メッセージ
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <h2>
        TOP　新着メッセージ
      </h2>
      <div class="message_list">
        {% if message_list %}
          {% for message in message_list %}
            <a href='javascript:getPage("{% url 'admin_view:adminMessage' user_id=message.user__id %}")'>
              <div class="message">
                <div class="row no-gutters">
                  <div class="col-md-2">
                    <div class="message-icon">
                      <img src="">
                    </div>
                    <h3 class="send_name">
                      {{ message.user__name }}
                    </h3>
                  </div>
                  <div class="col-md-10">
                    <h4 class="message__text {{ message.admin_send_flag|yesno:"admin_send,user_send" }}">
                      {{ message.text|linebreaksbr }}
                    </h4>
                  </div>
                </div>
              </div>
            </a>
          {% endfor %}
          {% else %}
            <h3 class="no-message">新着メッセージはありません</h3>
        {% endif %}
      </div>
    </div>
    <div class="container">
      <div class="pagination">
        <div class="row no-gutters">
          {% if message_list %}
            {% for page in pages %}
              <div class="col-md-1">
                <a href='javascript:getPage("{% url 'admin_view:adminMessageListWithPage' s_page=page %}")'>
                  <button class="page-button">
                    {{ page }}
                  </button>
                </a>
              </div>
            {% endfor %}
            {% else %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}