cei/admin_view/urls.py
from django.conf.urls import url
from admin_view import views, templates


urlpatterns = [
  url(r'^$', views.adminTop, name='adminTop'),
  url(r'^admin_login/$', views.adminLogin, name='adminLogin'),
  url(r'^user_list/$', views.adminUserList, name='adminUserList'),
  url(r'^user_create/$', views.adminUserEdit, name='adminUserCreate'),
  url(r'^user_single/(?P<user_id>.{1,16})/$', views.adminUserSingle, name='adminUserSingle'),
  url(r'^user_edit/(?P<user_id>.{1,16})/$', views.adminUserEdit, name='adminUserEdit'),
  url(r'^user_delete/(?P<user_id>.{1,16})/$', views.adminUserDelete, name='adminUserDelete'),
  url(r'^user_activate/(?P<user_id>.{1,16})/$', views.adminUserActivate, name='adminUserActivate'),
  url(r'^user_list_deleted/$', views.adminUserListDeleted, name='adminUserListDeleted'),
  url(r'^user_list_search/$', views.adminUserSearch, name='adminUserSearch'),
  url(r'^news_list_admin/$', views.newsListAdmin, name='newsListAdmin'),
  url(r'^news_list_admin/(?P<s_page>\d+)/$', views.newsListAdmin, name='newsListWithPageAdmin'),
  url(r'^news_single_admin/(?P<id>.+)/$', views.newsSingleAdmin, name='newsSingleAdmin'),
  url(r'^news_create/$', views.newsEdit, name='newsCreate'),
  url(r'^news_edit/(?P<id>.+)/$', views.newsEdit, name='newsEdit'),
  url(r'^news_delete/(?P<id>.+)/$', views.newsDelete, name='newsDelete'),
  url(r'^category_list/$', views.categoryList, name='categoryList'),
  url(r'^category_create/$', views.categoryEdit, name='categoryCreate'),
  url(r'^category_edit/(?P<id>.+)/$', views.categoryEdit, name='categoryEdit'),
  url(r'^message/(?P<user_id>\w+)/$', views.adminMessage, name="adminMessage"),
  url(r'^message/(?P<user_id>\w+)/(?P<s_page>\d+)/$', views.adminMessage, name="adminMessageWithPage"),
  url(r'^message_list/$', views.adminMessageList, name="adminMessageList"),
  url(r'^message_list/(?P<s_page>\d+)/$', views.adminMessageList, name='adminMessageListWithPage'),
]

cei/cei/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from news import views
from cei import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^admin_view/', include('admin_view.urls', namespace='admin_view')),
    url(r'^account/', include('userManagement.urls', namespace='user_management')),
    url(r'^message/', include('message.urls', namespace='message')),
]

cei/news/urls.py
from django.conf.urls import url
from news import views, templates

urlpatterns = [
  url(r'^$', views.newsList, name='newsList'),
  url(r'^(?P<s_page>\d+)/$', views.newsList, name='newsListWithPage'),
  url(r'^news_single/(?P<id>.+)/$', views.newsSingle, name='newsSingle'),
]

cei/news/models/category.py
from django.db import models
from colorfield.fields import ColorField

class Category(models.Model):
  category_name = models.CharField(max_length=16, null=False, blank=False)
  category_color = ColorField(max_length=8, null=False, blank=False)

  def __str__(self):
    return self.category_name

cei/news/models/news.py
from django.db import models
from news.models.category import *

class News(models.Model):
  # news_image = models.ImageField()
  news_category = models.ForeignKey(Category, null=False, blank=False, default=0)
  title = models.CharField(max_length=256, null=False, blank=False)
  caption = models.CharField(max_length=8192, null=False, blank=False)
  views = models.CharField(max_length=16)
  post_datetime = models.DateTimeField(auto_now=False, auto_now_add=True)
  watch_flg = models.BooleanField(default=True)
  enabled = models.BooleanField(default=True)

  def __str__(self):
    return "{} {}".format(self.title, self.caption[:20])

cei/news/forms.py
from django.forms import ModelForm, RadioSelect, Textarea, ValidationError, HiddenInput, BooleanField
from .models.news import *
from django.forms.widgets import TextInput

class newsForm(ModelForm):
  class Meta:
    model = News
    fields = (
      'news_category', 'title', 'caption', 'watch_flg',
    )
    widgets = {
      'caption': Textarea,
      'watch_flg' : RadioSelect(choices=((True, 'ON',), (False, 'OFF',)))
    }

  def __init__(self, *args, **kwargs):
    kwargs.setdefault('label_suffix', '')
    super(newsForm, self).__init__(*args, **kwargs)


class categoryForm(ModelForm):
  class Meta:
    model = Category
    fields = (
      'category_name', 'category_color',
    )

  def __init__(self, *args, **kwargs):
    kwargs.setdefault('label_suffix', '')
    super(categoryForm, self).__init__(*args, **kwargs)
    # self.fields['category_name'].widget.attrs.update({'class': 'color'})

cei/news/views.py
from django.shortcuts import render
import math
from .forms import *
from userManagement.models.user import *
from django.contrib import messages

def newsList(request, s_page = '1'):
  if request.method == 'GET' or 'cei_id' not in request.POST:
    messages.info(request, 'ログインしてください。')
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_work = User.objects.filter(id=user_id)
    if user_work.count() == 0:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'user_login.html')
    else:
      page = int('0' + s_page)
      news_data = News.objects.filter(watch_flg=True, enabled = True).order_by('-post_datetime')
      last_page = int(math.ceil(news_data.count() / 6))
      pages = []
      for i in range(last_page):
        pages.append(i + 1)
      news_list = news_data[(page - 1) * 6:page * 6].values('post_datetime', 'news_category__category_name', 'title', 'news_category__category_color', 'id')
      return render(request, 'news_list.html', dict(news_list=news_list, pages=pages))


def newsSingle(request, id = None):
  if request.method == 'GET' or 'cei_id' not in request.POST:
    messages.info(request, 'ログインしてください。')
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_work = User.objects.filter(id=user_id)
    if user_work.count() == 0:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'user_login.html')
    else:
      if id:
        news = News.objects.filter(id = id, watch_flg=True, enabled = True).values('post_datetime', 'news_category__category_name', 'caption', 'title', 'news_category__category_color')[0]
        if news:
          return render(request, 'news_single.html', dict(news=news))
        else:
          messages.info(request, 'ニュースが存在しません。')
          return render(request, 'news_list.html')
      else:
          messages.info(request, '不正なアクセスです。')
          return render(request, 'news_list.html')

cei/news/templates/admin_category_create.html
{% extends "admin_base.html" %}

{% block title %}新規カテゴリー{% endblock title %}

{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       管理者専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ追加
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
  {% if id %}
    <form action="{% url 'admin_view:categoryEdit' id=id %}" method="post">
  {% else %}
    <form action="{% url 'admin_view:categoryCreate' %}" method="post">
  {% endif %}
    {% csrf_token %}
      <input type="hidden" name="post_type" value="post">
      <div class="main-item">
        <div class="row">
          <div class="col-md-3 news-text">
             カテゴリータイトル <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
            {{ form.category_name }}
          </div>
          <div class="col-md-3 news-text">
             カテゴリーカラー <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
                {{ form.category_color }}
          </div>
        </div>
        {% if id %}
          <div class="text-right">
            <button type="submit" id="submit-category" class="submit-btn">変更</button>
          </div>
        {% else %}
          <div class="text-right">
            <button type="submit" id="submit-category" class="submit-btn">新規作成</button>
          </div>
        {% endif %}
      </div>
    </form>
  </form>
{% endblock content %}

cei/news/templates/admin_category_list.html
{% extends "admin_base.html" %}

{% block title %}{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        お知らせ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <span>
        >
      </span>
      <h4>
        カテゴリー管理
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <h2>
        カテゴリー管理
      </h2>
      <div class="row news-border category-tag">
        {% for category in category_list %}
          <div class="col-md-2">
            <a href='javascript:getPage("{% url 'admin_view:categoryEdit' id=category.id %}")'>
              <h4 style="background-color:{{ category.category_color }};">
                {{ category.category_name }}
              </h4>
            </a>
          </div>
        {% endfor %}
      </div>
      <a href='javascript:getPage("{% url 'admin_view:categoryCreate' %}")'>
        <div class="category-create-list-btn">
          ＋新規カテゴリー投稿
        </div>
      </a>
      <a href='javascript:getPage("{% url 'admin_view:newsCreate' %}")'>
        <div class="news-create-list-btn">
          ＋新規ニュース投稿
        </div>
      </a>
    </div>
  </div>

{% endblock content %}

cei/news/templates/admin_news_create.html
{% extends "admin_base.html" %}

{% block title %}新規ニュース{% endblock title %}

{% block content %}
  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       管理者専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ追加
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
  {% if id %}
    <form action="{% url 'admin_view:newsEdit' id=id %}" method="post">
  {% else %}
    <form action="{% url 'admin_view:newsCreate' %}" method="post">
  {% endif %}
    {% csrf_token %}
      <input type="hidden" name="post_type" value="post">
      <div class="main-item">
        <div class="row">
          <div class="col-md-3 news-text">
             ニュースカテゴリー <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
            {{ form.news_category }}
            <a href='javascript:getPage("{% url 'admin_view:categoryCreate'%}")'>
              <h5>
                ＋追加
              </h5>
            </a>
          </div>
          <div class="col-md-3 news-text">
             ニュースタイトル <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
                {{ form.title }}
          </div>
          <div class="col-md-3 news-text">
                ニュース本文 <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
                {{ form.caption }}
          </div>
          <div class="col-md-3 news-text">
                ニュース表示 <span class="required-span">必須</span>
          </div>
          <div class="col-md-9 news-caption">
                {{ form.watch_flg }}
          </div>
        </div>
        <div class="text-right">
          <button type="submit" id="submit" class="submit-btn">投稿</button>
          {% if id %}
            <div id="delete-btn">
              削除
            </div>
          {% endif %}
        </div>
      </div>
    </form>
  </div>
{% endblock content %}
{% block js %}
  <script>
    $('#delete-btn').click(function(){
      bootbox.confirm("本当に削除しますか？", function(result){
        if(result){
          var form = document.createElement( 'form' );
          document.body.appendChild( form );
          var post_type = document.createElement( 'input' );
          post_type.setAttribute( 'type' , 'hidden' );
          post_type.setAttribute( 'name' , 'post_type' );
          post_type.setAttribute( 'value' , 'user_form' );
          var admin_id = document.createElement( 'input' );
          admin_id.setAttribute( 'type' , 'hidden' );
          admin_id.setAttribute( 'name' , 'admin_id' );
          admin_id.setAttribute( 'value' , localStorage.getItem('admin_id') );
          var admin_pass = document.createElement( 'input' );
          admin_pass.setAttribute( 'type' , 'hidden' );
          admin_pass.setAttribute( 'name' , 'admin_pass' );
          admin_pass.setAttribute( 'value' , localStorage.getItem('admin_pass') );
          var csrftoken = document.createElement( 'input' );
          csrftoken.setAttribute( 'type' , 'hidden' );
          csrftoken.setAttribute( 'name' , 'csrfmiddlewaretoken' );
          csrftoken.setAttribute( 'value' , $.cookie('csrftoken') );
          form.appendChild( post_type );
          form.appendChild( admin_id );
          form.appendChild( admin_pass );
          form.appendChild( csrftoken );
          form.setAttribute( 'action' , "{% url 'admin_view:newsDelete' id=id %}" );
          form.setAttribute( 'method' , 'post' );
          form.submit();
{#          location.href = "{% url 'admin_view:newsDelete' id=id %}";#}
        }
      });
    });
  </script>
{% endblock %}

cei/news/templates/admin_news_list.html
{% extends "admin_base.html" %}

{% block title %}{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        お知らせ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <h2>
        お知らせ
      </h2>
      <a href='javascript:getPage("{% url 'admin_view:newsCreate' %}")'>
        <div class="news-create-btn">
          ＋新規投稿
        </div>
      </a>
      <a href='javascript:getPage("{% url 'admin_view:categoryList' %}")'>
        <div class="category-create-btn">
          ＋カテゴリー編集
        </div>
      </a>
      {% for news in news_list %}
        <a href='javascript:getPage("{% url 'admin_view:newsSingleAdmin' id=news.id %}")'>
          <div class="row news-border">
            <div class="col-md-2">
              <h3>
                {{ news.post_datetime|date:"Y/m/d"}}
              </h3>
              <h4 style="background-color:{{ news.news_category__category_color }};">
                {{ news.news_category__category_name }}
              </h4>
            </div>
            <div class="col-md-10">
              <p>
                {{ news.title }}
              </p>
            </div>
          </div>
        </a>
      {% endfor %}
      <div class="paging-box">
        {% for page in pages %}
          <a href='javascript:getPage("{% url 'admin_view:newsListWithPageAdmin' s_page=page %}")'>
            <button class="pages-btn">
              {{ page }}
            </button>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

cei/news/templates/admin_news_single.html
{% extends "admin_base.html" %}

{% block title %}{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       お知らせ管理
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ詳細
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <h2 class="main-item-title">
        お知らせ
      </h2>
      <a href='javascript:getPage("{% url 'admin_view:newsEdit' id=news.id %}")'>
        <button class="edit-news-btn">
          お知らせ編集
        </button>
      </a>
      <div class="row news-border single-opacity">
        <div class="col-md-2">
          <h3>
            {{ news.post_datetime|date:"Y/m/d"}}
          </h3>
          <h4 style="background-color:{{ news.news_category__category_color }};">
            {{ news.news_category__category_name }}
          </h4>
        </div>
        <div class="col-md-10 right-news">
          <h3>
            {{ news.title }}
          </h3>
          <p>
            {{ news.caption|linebreaksbr }}
          </p>
        </div>
      </div>
      <div class="paging-box">
        <a href='javascript:getPage("{% url 'admin_view:newsListAdmin' %}")'>
          <button class="back-news-btn">
            一覧へ戻る
          </button>
        </a>
      </div>
    </div>
  </div>

{% endblock content %}

cei/news/templates/news_list.html
{% extends "base.html" %}

{% block title %}ニュースリスト{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <h4 class="user-box-name">
        <span class="insert-user-rank-name insert-user-rank-color"></span>
        <span class="insert-user-name"></span>
        様
      </h4>
    </div>
    <div class="main-item">
      <h2>
        お知らせ
      </h2>
      {% for news in news_list %}
        <a href='javascript:getPage("{% url 'news:newsSingle' id=news.id %}")'>
          <div class="row news-border">
            <div class="col-md-2">
              <h3>
                {{ news.post_datetime|date:"Y/m/d"}}
              </h3>
              <h4 style="background-color:{{ news.news_category__category_color }};">
                {{ news.news_category__category_name }}
              </h4>
            </div>
            <div class="col-md-10">
              <p>
                {{ news.title }}
              </p>
            </div>
          </div>
        </a>
      {% endfor %}
      <div class="paging-box">
        {% for page in pages %}
          <a href='javascript:getPage("{% url 'news:newsListWithPage' s_page=page %}")'>
            <button class="pages-btn">
              {{ page }}
            </button>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

cei/news/templates/news_single.html
{% extends "base.html" %}

{% block title %}ニュース詳細{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ一覧
      </h4>
      <span>
        >
      </span>
      <h4>
        お知らせ詳細
      </h4>
      <h4 class="user-box-name">
        <span class="insert-user-rank-name insert-user-rank-color"></span>
        <span class="insert-user-name"></span>
        様
      </h4>
    </div>
    <div class="main-item">
      <h2>
        お知らせ
      </h2>
      <div class="row news-border">
        <div class="col-md-2">
          <h3>
            {{ news.post_datetime|date:"Y/m/d"}}
          </h3>
          <h4 style="background-color:{{ news.news_category__category_color }};">
            {{ news.news_category__category_name }}
          </h4>
        </div>
        <div class="col-md-10 right-news">
          <h3>
            {{ news.title }}
          </h3>
          <p>
            {{ news.caption|linebreaksbr }}
          </p>
        </div>
      </div>
      <div class="paging-box">
        <a href='javascript:getPage("{% url 'news:newsList'%}")'>
          <button class="back-news-btn">
            一覧へ戻る
          </button>
        </a>
      </div>
    </div>
  </div>

{% endblock content %}