cei/admin_view/urls.py
from django.conf.urls import url
from admin_view import views, templates


urlpatterns = [
  url(r'^$', views.adminTop, name='adminTop'),
  url(r'^admin_login/$', views.adminLogin, name='adminLogin'),
  url(r'^user_list/$', views.adminUserList, name='adminUserList'),
  url(r'^user_create/$', views.adminUserEdit, name='adminUserCreate'),
  url(r'^user_single/(?P<user_id>.{1,16})/$', views.adminUserSingle, name='adminUserSingle'),
  url(r'^user_edit/(?P<user_id>.{1,16})/$', views.adminUserEdit, name='adminUserEdit'),
  url(r'^user_delete/(?P<user_id>.{1,16})/$', views.adminUserDelete, name='adminUserDelete'),
  url(r'^user_activate/(?P<user_id>.{1,16})/$', views.adminUserActivate, name='adminUserActivate'),
  url(r'^user_list_deleted/$', views.adminUserListDeleted, name='adminUserListDeleted'),
  url(r'^user_list_search/$', views.adminUserSearch, name='adminUserSearch'),
  url(r'^news_list_admin/$', views.newsListAdmin, name='newsListAdmin'),
  url(r'^news_list_admin/(?P<s_page>\d+)/$', views.newsListAdmin, name='newsListWithPageAdmin'),
  url(r'^news_single_admin/(?P<id>.+)/$', views.newsSingleAdmin, name='newsSingleAdmin'),
  url(r'^news_create/$', views.newsEdit, name='newsCreate'),
  url(r'^news_edit/(?P<id>.+)/$', views.newsEdit, name='newsEdit'),
  url(r'^news_delete/(?P<id>.+)/$', views.newsDelete, name='newsDelete'),
  url(r'^category_list/$', views.categoryList, name='categoryList'),
  url(r'^category_create/$', views.categoryEdit, name='categoryCreate'),
  url(r'^category_edit/(?P<id>.+)/$', views.categoryEdit, name='categoryEdit'),
  url(r'^message/(?P<user_id>\w+)/$', views.adminMessage, name="adminMessage"),
  url(r'^message/(?P<user_id>\w+)/(?P<s_page>\d+)/$', views.adminMessage, name="adminMessageWithPage"),
  url(r'^message_list/$', views.adminMessageList, name="adminMessageList"),
  url(r'^message_list/(?P<s_page>\d+)/$', views.adminMessageList, name='adminMessageListWithPage'),
]

cei/cei/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from news import views
from cei import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^admin_view/', include('admin_view.urls', namespace='admin_view')),
    url(r'^account/', include('userManagement.urls', namespace='user_management')),
    url(r'^message/', include('message.urls', namespace='message')),
]

cei/message/urls.py
from django.conf.urls import url
from message import views

urlpatterns = [
  url(r'^$', views.message, name="message"),
  url(r'^(?P<s_page>\d+)/$', views.message, name="messageWithPage"),
]

cei/message/models/message.py
from django.db import models
from userManagement.models.user import *

class Message(models.Model):
  user = models.ForeignKey(User)
  text = models.CharField(max_length=8192, null=False, blank=False)
  send_datetime = models.DateTimeField(auto_now=False, auto_now_add=True)
  admin_send_flag = models.BooleanField()
  read_flag = models.BooleanField(default=False)
  enabled = models.BooleanField(default=True)

  def __str__(self):
    return "{} {}".format(self.user, self.admin_send_flag, self.text[:20])

cei/message/views.py
from django.shortcuts import render
from .models.message import *
from django.contrib import messages
import math

def message(request, s_page = '1'):
  if request.method == 'GET' or 'cei_id' not in request.POST:
    messages.info(request, 'ログインしてください。')
    return render(request, 'user_login.html')
  else:
    user_id = request.POST['cei_id']
    user_work = User.objects.filter(id=user_id)
    if user_work.count() == 0:
      messages.info(request, '不正なアクセスです。')
      return render(request, 'user_login.html')
    else:
      if request.POST['post_type'] == 'get_page':
        page = int(s_page)
        message_count = int(math.ceil(Message.objects.filter(user_id=user_id, enabled=True).count() / 10))
        pages = []
        for i in range(message_count):
          pages.append(i + 1)
        message_data = Message.objects.filter(user_id=user_id, enabled=True).values('user__name', 'text', 'send_datetime', 'admin_send_flag').order_by('-send_datetime')[(page - 1) * 10:page * 10]
        message_count = message_data.count()
        message_list = [''] * message_count
        for idx, message in enumerate(message_data):
          message_list[message_count - idx - 1] = message
        Message.objects.filter(user_id=user_id, enabled=True, admin_send_flag=True, read_flag=False).update(read_flag=True)
        return render(request, 'message.html', dict(message_list=message_list, pages=pages))
      else:
        message = Message()
        message.user = User.objects.get(id=user_id)
        message.text = request.POST['text']
        message.admin_send_flag = False
        message.save()
        page = int(s_page)
        message_count = int(math.ceil(Message.objects.filter(user_id=user_id, enabled=True).count() / 10))
        pages = []
        for i in range(message_count):
          pages.append(i + 1)
        message_data = Message.objects.filter(user_id=user_id, enabled=True).values('user__name', 'text', 'send_datetime', 'admin_send_flag').order_by('-send_datetime')[(page - 1) * 10:page * 10]
        message_count = message_data.count()
        message_list = [''] * message_count
        for idx, message in enumerate(message_data):
          message_list[message_count - idx - 1] = message
        return render(request, 'message.html', dict(message_list=message_list, pages=pages))

cei/message/templates/admin_message.html
{% extends "admin_base.html" %}

{% load staticfiles %}

{% block title %}{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        メッセージ
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <h2>
        メッセージ
      </h2>
      <div class="message_list">
        {% for message in message_list %}
          <div class="message">
            <div class="row no-gutters">
              <div class="col-md-2">
                {% if message.admin_send_flag %}
                  <div class="message-icon">
                    <img src="{% static 'img/admin-img.png' %}">
                  </div>
                  <h3 class="send_name">
                    CEI
                  </h3>
                  {% if message.read_flag %}
                    <h4 class="message__read required-span">
                      既読
                    </h4>
                  {% else %}
                    <h4 class="message__read optional-span">
                      未読
                    </h4>
                  {% endif %}
                {% else %}
                  <div class="message-icon">
                    <img src="{% static 'img/you-img.png' %}">
                  </div>
                  <h3 class="send_name">
                    {{ message.user__name }}
                  </h3>
                {% endif %}
              </div>
              <div class="col-md-10">
                <h4 class="message__text {{ message.admin_send_flag|yesno:"admin_send,user_send" }}">
                  {{ message.text|linebreaksbr }}
                </h4>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="pagination">
        {% for page in pages %}
          <a href='javascript:getPage("{% url 'admin_view:adminMessageWithPage' user_id=user_id s_page=page %}")'>
            <button class="page-button">
              {{ page }}
            </button>
          </a>
        {% endfor %}
      </div>
      <div class="message-send-box">
        <div class="message-icon">
          <img src="{% static 'img/admin-img.png' %}">
        </div>
        <h3 class="send_name">
          CEI <span>からメッセージを送信する</span>
        </h3>
        <div class="row no-gutters">
          <div class="col-md-2">
            <h4>
              テキスト内容
            </h4>
          </div>
          <div class="col-md-10">
            <form action="{% url 'admin_view:adminMessage' user_id=user_id %}" method="POST" class="message-send-form">
              {% csrf_token %}
              <input type="hidden" name="post_type" value="post">
              <textarea title="message_text" name="text"></textarea>
              <button type="submit">
                メッセージを送信する
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

cei/message/templates/admin_message_list.html
{% extends "admin_base.html" %}

{% block title %}{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
       会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        メッセージ一覧
      </h4>
      <h4 class="cei-icon">
        管理者<span>CEI</span>
      </h4>
    </div>
    <div class="main-item">
      <div class="container">
        <h2>
          新着メッセージ一覧
        </h2>
        <div class="message_list">
          {% if message_list %}
            {% for message in message_list %}
              <a href='javascript:getPage("{% url 'admin_view:adminMessage' user_id=message.user__id %}")'>
                <div class="message">
                  <div class="row no-gutters">
                    <div class="col-md-2">
                      <div class="message-icon">
                        <img src="">
                      </div>
                      <h3 class="send_name">
                        {{ message.user__name }}
                      </h3>
                    </div>
                    <div class="col-md-10">
                      <h4 class="message__text {{ message.admin_send_flag|yesno:"admin_send,user_send" }}">
                        {{ message.text|linebreaksbr }}
                      </h4>
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
            {% else %}
            <h3 class="no-message">新着メッセージはありません</h3>
          {% endif %}
        </div>
      </div>
      <div class="container">
        <div class="pagination">
          <div class="row no-gutters">
            {% if message_list %}
              {% for page in pages %}
                <div class="col-md-1">
                  <a href='javascript:getPage("{% url 'admin_view:adminMessageListWithPage' s_page=page %}")'>
                    <button class="page-button">
                      {{ page }}
                    </button>
                  </a>
                </div>
              {% endfor %}
              {% else %}
            {% endif %}
          </div>
        </div>
      </div>
  </div>
{% endblock content %}

cei/message/templates/message.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}メッセージ{% endblock title %}

{% block content %}

  <div class="org-container">
    <div class="bread-crumb">
      <h4>
        会員様専用ページ
      </h4>
      <span>
        >
      </span>
      <h4>
        メッセージ
      </h4>
      <h4 class="user-box-name">
        <span class="insert-user-rank-name insert-user-rank-color"></span>
        <span class="insert-user-name"></span>
        様
      </h4>
    </div>
    <div class="main-item">
      <h2>
        メッセージ
      </h2>
      <div class="message_list">
        {% for message in message_list %}
          <div class="message">
            <div class="row no-gutters">
              <div class="col-md-2">
                {% if message.admin_send_flag %}
                  <div class="message-icon">
                    <img src="{% static 'img/admin-img.png' %}">
                  </div>
                  <h3 class="send_name">
                    CEI
                  </h3>
                {% else %}
                  <div class="message-icon">
                    <img src="{% static 'img/you-img.png' %}">
                  </div>
                  <h3 class="send_name insert-user-name">
                  </h3>
                {% endif %}
              </div>
              <div class="col-md-10">
                <h4 class="message__text {{ message.admin_send_flag|yesno:"admin_send,user_send" }}">
                  {{ message.text|linebreaksbr }}
                </h4>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="pagination">
        {% for page in pages %}
          <a href='javascript:getPage("{% url 'message:messageWithPage' s_page=page %}")'>
            <button class="page-button">
              {{ page }}
            </button>
          </a>
        {% endfor %}
      </div>
      <div class="message-send-box">
        <div class="message-icon">
          <img src="{% static 'img/you-img.png' %}">
        </div>
        <h3 class="send_name">
          <span class="insert-user-name"></span> <span>からメッセージを送信する</span>
        </h3>
        <div class="row no-gutters">
          <div class="col-md-2">
            <h4>
              テキスト内容
            </h4>
          </div>
          <div class="col-md-10">
            <form action="{% url 'message:message' %}" method="POST" class="message-send-form">
              {% csrf_token %}
              <input type="hidden" name="post_type" value="post">
              <input type="hidden" name="cei_id" class="input-cei-id">
              <textarea title="message_text" name="text"></textarea>
              <button type="submit">
                メッセージを送信する
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}